### ISSUE TITLE
iStats command path not compatible with OSX Yosemite

### ISSUE THREAD

**Issue by ivanbacher** [roele/istats.widget#5]
Not sure if this is an issue, but I had to change the iStats command path in index.js to `command: 'iStats'`

**Comment by roele** [comment]
@BuildingJarl Can you provide any hints about your setup (OS version, Ruby version, using RVM, etc.)?

**Comment by ivanbacher** [comment]
Sure. 

```
OSX 10.10.5,

ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

```

**Comment by roele** [comment]
Looks like in OSX 10.10.5 the Gem will be installed in `/usr/bin/iStats` instead of `/usr/local/bin/iStats`.

**Comment by thesp0nge** [comment]
Nothing appeared. No error... just... nothing.

<div id="istats-widget-index-js" class="widget"><div id="stats" style="color: #fff; top:0px; left:0px; "></div></div>

But running istats.sh from command line resulted in a crash. A segfault because system wide ruby was called to execute my rvm gem.

So i changed the script to: command=( rvm-exec "$(which iStats)" )
And again, on desktop nothing it has been shown but form command line, script works:
--- CPU Stats ---
CPU temp: 63.375°C  ▁▂▃▅▆▇

--- Fan Stats ---
Total fans in system: 1
Fan 0 speed: 1982.0 RPM  ▁▂▃▅▆▇

--- Battery Stats ---
Battery health: Good
Cycle count: 130  ▁▂▃▅▆▇  13.0%
Max cycle count: 1000
Current charge:  5577 mAh  91%
Maximum charge:  6099 mAh ▁▂▃▅▆▇  91.0%
Design capacity: 6700 mAh
Battery temp: 31.3°C

For more stats run `istats extra` and follow the instructions.

:-(
